eol-uchile/edx-staging

requirements/private.txt
=> Fix SSO admin search

requirements/private.txt
=> Updating eolzoom

.github/workflows/docker.yml, Dockerfile, requirements/private.txt
=> Remove testing version

requirements/private.txt
=> Updating eol-zoom-xblock

requirements/private.txt
=> Update zoom xblock

Dockerfile
=> Updating edx version

Dockerfile, requirements/private.txt
=> Updating uchileedxlogin with new information

Dockerfile
=> Updating theme for access requirements and platform

requirements/private.txt
=> Adding new plugin eol_contact_form

requirements/private.txt
=> Update eol_completion with async tasks

requirements/private.txt
=> Update contact form

Dockerfile
=> Update edx-platform version

requirements/private.txt
=> Updating zoom xblock

requirements/private.txt
=> Updating eolzoom after tests

Dockerfile
=> Update edx version

requirements/private.txt
=> Updating uchileedxlogin instructor registration information

.gitmodules
=> Adding edx-cursos-theme theme

.github/workflows/docker.yml, Dockerfile, requirements/private.txt
=> Update to juniper image, remove untested blocks

requirements/private.txt
=> Adding ubcpi xblock module

requirements/private.txt
=> Adding xblock_in_video_quiz xblock

requirements/private.txt
=> Adding updated scorm xblock

requirements/private.txt
=> Adding ported xblock-drag-and-drop-v2

requirements/private.txt
=> Adding free-text-response xblock

.gitmodules
=> Adding the ported eduonline theme

requirements/private.txt
=> Adding sence xblock

requirements/private.txt
=> Update eol list grade

requirements/private.txt
=> Zoom Youtube

requirements/private.txt
=> Update s3 to support boto3

.github/workflows/docker.yml, Dockerfile, default.conf
=> Compile and push static files

requirements/private.txt
https://github.com/pypa/setuptools/issues/2352
bors r+
=> Blacklist setuptools 50.0 while the build is not fixed

requirements/private.txt
It was causing crashes on workers`
bors r+
=> Rollback django-redis

requirements/private.txt
=> Update ora2 with s3 changes

.github/workflows/docker.yml, Dockerfile
=> Adding new s3 static images

Dockerfile
=> Switch to rclone, as aws cli is slow copying files

.github/workflows/docker.yml, Dockerfile
=> Remove deprecated image

Dockerfile
=> Update edx-platform with security fixes

requirements/private.txt
=> Update scorm xblock

Dockerfile
=> Build translations before collecting assets

Dockerfile
=> Move rebuild translation after theme build

requirements/private.txt
add testing corfo_generate_code and update eol_gradeforum_xblock
=> add testing corfo_generate_code

Dockerfile
Reverts eol-uchile/edx-staging#330
bors r+
=> Revert "Update edx-platform with new gunicorn jitter"

Dockerfile
=> Update edx-platform jitter

requirements/private.txt
=> Update xblock-lti with new parameter resource_link_title

requirements/private.txt
=> Adding patched super_csv

Dockerfile
=> Update edx-platform translations

Dockerfile
Include verification html tags and translations
=> Bump edx-platform version

requirements/private.txt
=> Update redis for Koa

Dockerfile
Require https://github.com/eol-uchile/edx-platform/runs/2767832889 to complete
=> Update edx-platform with latest koa changes

.github/workflows/docker.yml, Dockerfile
=> First lilac base image

requirements/private.txt
=> Update xblocks with import fixes

requirements/private.txt
=> Update imports on eol_feedback

.github/workflows/docker.yml, .mergify.yml
=> [Test ]Added Mergify for staging

.github/workflows/webhook.yml
=> Config for dependency between workflows
